### ISSUE TITLE
аим и его настройка

### ISSUE THREAD

**Issue by SHADOWSTEELYT** [reuke/surviv.io-cheat#10]
уважаемый, обьясните пожалуйста, как в чите настроить аим. за что отвечает каждый из ползунков, как сделать жесткий аим, как-беспалевный. очень надеюсь на ваш ответ

**Comment by reuke** [comment]
Беспалевность пока что ограничена значениями restrictions. Это ограничения по углу и расстоянию, чтобы прицел не дергалсян на 180 градусов. Расстояние имеет приоритет над углом, чтобы было проще убивать людей вблизи. Выстави поменьше, если хочешь - но тогда надо будет труднее прицеливаться. Можешь выключить вообще, но тогда будут возможны резкие развороты на 180 градусов и дергания.
Инерция отвечает за инертность в определении скорости и предполагаемого местоположения. Они полезны для людей с не очень хорошим интернетом и в некоторой степени сглаживают неточность или слишком высокую точность наведения. Их поведение в значительной степени зависит от твоего интернета и желаемого результата. Так что я советую просто поэкспериментировать и попробовать поиграть с разными значениями. Например, крайними для начала.
