### ISSUE TITLE
[Re-Opened]Not working when i join a game

### ISSUE THREAD

**Issue by EastArctica** [reuke/surviv.io-cheat#13]
this was working perfectly yesterday but i got on today and it just stopped working. When i open surviv.io the logo changes per usual to the one you set but when i join a Solo game nothing shows up i can hear the game in the background but nothing is happening (I am using chrome with latest update)

**Comment by EastArctica** [comment]
has to clear cache

**Comment by EastArctica** [comment]
Reopened i am on a chromebook this time but nothing is happening. Here is a screenshot of what it looks like 
![screenshot 2018-06-11 at 12 41 15 pm](https://user-images.githubusercontent.com/32211444/41245134-2eab5a5e-6d75-11e8-9c70-28f3daaa3599.png)
if anyone would help that would be great

**Comment by reuke** [comment]
@EastArctica Thanks for report.
Check the last version (0.15 or higher), and make sure that no other extensions is interfering with this game.
If it will no help, provide some console logs, please (F12).

**Comment by reuke** [comment]
Too old actually.
