### ISSUE TITLE
Extension no longer works

### ISSUE THREAD

**Issue by tmings** [reuke/surviv.io-cheat#17]
Earlier today, the extension worked beautifully, but I revisited the game about 2-3 hours later and it no longer works. It is just the normal game, even though the surviv.io logo is still changed. Any ways to fix?

**Comment by Koksupl1234** [comment]
I have got this same problem creator pleas help :)

**Comment by publiwebhnventas** [comment]
working version: https://github.com/publiwebhnventas/surviv.io-cheat

Steps:
1. Download as zip
2. Open Google Chrome
3. Go to extensions
4. Activate developer mode
5. Upload extension without packing
