### ISSUE TITLE
Not working - detected by servers?

### ISSUE THREAD

**Issue by robertkent87** [reuke/surviv.io-cheat#18]
Since this evening it's stopped working for me, The extension is up to date 0.14.8 and the cheat menu shows in-game but none of the functions work. There no errors in the console either

![surviv io - 2d battle royale game - google chrome 2018-06-27 21 51 23](https://user-images.githubusercontent.com/1167648/41999177-bb324bea-7a54-11e8-820c-737bc7e29203.png)

**Comment by Koksupl1234** [comment]
This same problem in my computer

**Comment by publiwebhnventas** [comment]
working version: https://github.com/publiwebhnventas/surviv.io-cheat

Steps:
1. Download as zip
2. Open Google Chrome
3. Go to extensions
4. Activate developer mode
5. Upload extension without packing

**Comment by reuke** [comment]
Fixed via #21
