### ISSUE TITLE
Not working anybody help ?

### ISSUE THREAD

**Issue by Koksupl1234** [reuke/surviv.io-cheat#19]
![image](https://user-images.githubusercontent.com/40644618/41999487-ea8b5c7a-7a5d-11e8-91a5-a325f9a643d5.png)
In morning work perfect but now its fixed  
![image](https://user-images.githubusercontent.com/40644618/41999834-1f815bfe-7a5f-11e8-989b-92acd6137d43.png)
screenshot console

**Comment by publiwebhnventas** [comment]
working version: https://github.com/publiwebhnventas/surviv.io-cheat

Steps:
1. Download as zip
2. Open Google Chrome
3. Go to extensions
4. Activate developer mode
5. Upload extension without packing

**Comment by Zimm1** [comment]
Fork my commit at least, that's a cheap steal of my work 😂

**Comment by reuke** [comment]
Fixed via #21

**Comment by publiwebhnventas** [comment]
@Zimm1 sorry man I just wanted to share the cheat
