### ISSUE TITLE
[6/28/18] CHEAT NOT WORKING

### ISSUE THREAD

**Issue by Helixable** [reuke/surviv.io-cheat#22]
Can you fix the cheat or tell us how to fix it?
It's not working. Nothing is. No aimbot, see-through or net lag. :( I think you guys are awesome! PLEASE FIX IT XD

**Comment by publiwebhnventas** [comment]
working version: https://github.com/publiwebhnventas/surviv.io-cheat

Steps:
1. Download as zip
2. Open Google Chrome
3. Go to extensions
4. Activate developer mode
5. Upload extension without packing

**Comment by reuke** [comment]
Fixed via #21
