### ISSUE TITLE
Why this cheat isn't working anymore.

### ISSUE THREAD

**Issue by Imbuzisurviv** [reuke/surviv.io-cheat#23]
There's a new update for surviv.io. Which means they have new patches. They probably patched this so the developer of this cheat needs to update this cheat for the "Sun's Out, Gun's Out" update.
This is why this cheat doesn't work anymore.
This cheat is also the best one so far.
PLEASE UPDATE THIS CHEAT DEVELOPERS!

**Comment by reuke** [comment]
Fixed via #21
