### ISSUE TITLE
Dont work since 28.06

### ISSUE THREAD

**Issue by Experte9** [reuke/surviv.io-cheat#24]
title...

**Comment by publiwebhnventas** [comment]
omg again

**Comment by publiwebhnventas** [comment]
@reuke again webpack inject thing

**Comment by Experte9** [comment]
works in 0.15.1 now, Thx

**Comment by reuke** [comment]
Ids was changed again. In case of repeating same issue we can find new way to get desired objects.
https://github.com/reuke/surviv.io-cheat/commit/721557e78e01c1b4f847505c21e3e214a161aa18

**Comment by publiwebhnventas** [comment]
@reuke how do you find objets ids?

**Comment by reuke** [comment]
@publiwebhnventas for now i dont have to do it frequently so i just doing it manually. It's not hard to just search for some particular known variables and copypast new id's. But if this ids gonna change every day i will automate it.

**Comment by Experte9** [comment]
Dont work again...

**Comment by publiwebhnventas** [comment]
@reuke then, do it, because it doesn't works once again

**Comment by publiwebhnventas** [comment]
it is hard for me to find those ids inside app.js

**Comment by Kalaborative** [comment]
Which particular variables are we looking for? Or if we could get [Zimm1](https://github.com/Zimm1) to chime in on this as well, it would be helpful. 👍

**Comment by Kalaborative** [comment]
@publiwebhnventas I've made a patch for this on my own fork.

**Comment by Kalaborative** [comment]
Here's actually how I managed to figure it out: Using Web Archive, I found matches with the IDs in the first commit with those in a previous version of the site's source code. I then found patterns with that and the current source code and found which ID strings went where. Took a bit of time to come to this conclusion but now it should be much easier (manually of course...) An automated process though would be ideal! 😂

**Comment by Koksupl1234** [comment]
dont work again

**Comment by publiwebhnventas** [comment]
@Kalaborative his forked version works (06/30/2018 @9:54 a.m.)

**Comment by robertkent87** [comment]
That fork crashes the game for me as soon as I open a crate

**Comment by Kalaborative** [comment]
I'll need to look at it again, because some reason the autoaim is also not as accurate as before. Not sure how, exactly.

**Comment by publiwebhnventas** [comment]
maybe the owners found the github, lets pass to bitbucket xd (private repo)

**Comment by ayushajain** [comment]
@Kalaborative's fork works if you turn off autoloot. I believe they changed the ids of the game items.

**Comment by Kalaborative** [comment]
I also turned off auto aim restriction and ironically auto aim works as well.

**Comment by reuke** [comment]
Fixed: https://github.com/reuke/surviv.io-cheat/commit/f80e85098ee0210c32c481a055f544e25b3ae6bf
Current version is 0.15.2.

**Comment by Koksupl1234** [comment]
New update new problems

**Comment by publiwebhnventas** [comment]
the guy has discovered the hack, lets move to a private repository.
