### ISSUE TITLE
Lines pointing to my team

### ISSUE THREAD

**Issue by IceHacks** [reuke/surviv.io-cheat#3]
Hey, I am trying out your cheats (works pretty good) although there are the lines pointing to my team to when I right click sometimes I shoot them instead of the enemy (I am now doing it in solo)

**Comment by reuke** [comment]
But in solo you don't have any team, right?

**Comment by ZXT-Tech** [comment]
He's talking about Duo/Squad games.
You should add the '!enemy.teammate' to the autoaim scope.

**Comment by reuke** [comment]
@ZXT-Tech It is [there](https://github.com/reuke/surviv.io-cheat/blob/4015aa56e8ffa8c18202e930fdabefd21799281f/payload/gameUpdate.js#L105) for a long time.

**Comment by ZXT-Tech** [comment]
No, it's not and that's why the autoaim is attached to your own team sometimes.

**Comment by reuke** [comment]
@IceHacks @ZXT-Tech [Fixed](https://github.com/reuke/surviv.io-cheat/commit/b3661adb2c1e51c838322a138afab951b5e04bd7).
